---
#
# Ansible managed
#
repository:
  description: Install and configure moodle on your system.
  homepage: https://buluma.co.ke/
  topics: system, monitoring, prometheus, ansible, molecule, tox, playbook, hacktoberfest
