---
roles:
  - name: buluma.bootstrap
  - name: buluma.python_pip
  - name: buluma.pip
  - name: buluma.setuptools
  - name: buluma.epel
  - name: buluma.buildtools
collections:
  - name: community.general
