---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- name: Install jmespath python package
  ansible.builtin.package:
    name: python3-jmespath

- name: Run preflight
  ansible.builtin.import_tasks:
    file: preflight.yml
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- name: Run install
  ansible.builtin.import_tasks:
    file: install.yml
  become: true
  tags:
    - prometheus_install

- name: Run configure
  ansible.builtin.import_tasks:
    file: configure.yml
  become: true
  tags:
    - prometheus_configure

- name: Ensure prometheus service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  tags:
    - prometheus_run
