---
- name: restart prometheus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: restarted

- name: reload prometheus
  ansible.builtin.service:
    name: prometheus
    state: reloaded
