---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    # - role: buluma.core_dependencies
    # - role: buluma.buildtools
    # - role: buluma.setuptools
    - role: buluma.pip
    - role: buluma.python_pip
      python_pip_modules:
        - name: jmespath
