---
#
# Ansible managed
#

name: Ansible Molecule

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/test.yaml'
  schedule:
    - cron: '20 4,7 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: test role install
      #  run: ansible-galaxy install buluma.prometheus

      - name: Run Playbook
        run: ansible-playbook --connection=local -i inventory.yml test.yml
