---
#
# Ansible managed
#

name: "Test Role"

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/test.yaml'
  schedule:
    - cron: '20 4,7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Test Role"
        run: ansible-playbook test.yml
