---
#
# Ansible managed
#

name: "Test Role"

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/test.yaml'
  schedule:
    - cron: '20 4,7 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test 
        run: ansible-galaxy install buluma.ansible_role_prometheus

      # - name: vrag
      #   run: vagrant up

      - name: "Test Role 1"
        run: ansible-playbook --connection=local -i inventory.yml test_playbook.yml

      # - name: test online role
      # run: ansible-galaxy install buluma.ansible_role_prometheus
